import type { Context } from 'hono';
import type { ContentfulStatusCode } from 'hono/utils/http-status';
import type { DrizzleDb } from '../db';
import type { iQuery } from '../utils/schema';
import { ErrorContext } from './error';

export type iContext = Context<
  {
    Bindings: Bindings;
    Variables: Variables;
  },
  '/',
  { in: { query: iQuery }; out: { query: iQuery } } & {
    in: { param: { id: string } };
    out: { param: { id: string } };
  } & { in: { json: any }; out: { json: any } }
>;

export interface Bindings {
  DB: D1Database;
  STORAGE: R2Bucket;
  CACHE: KVNamespace;
  API_RATE_LIMITER: RateLimit;
  FREE_USER_RATE_LIMITER: RateLimit;
  PAID_USER_RATE_LIMITER: RateLimit;
  JWT_SECRET: string;
  ENVIRONMENT: string;
  ENABLE_CASBIN?: string;
  /** Public R2.dev or custom domain base URL, e.g. https://pub-xxx.r2.dev */
  R2_PUBLIC_BASE_URL?: string;
}

export type Variables = {
  db: DrizzleDb;
  jwtPayload: {
    id: string;
    email: string;
    fullName: string | null;
    // roles array — supports multi-role RBAC; derived from user.role column at sign time
    roles: string[];
    exp: number;
    // jti is generated by nanoid(15) — string, not number
    jti: string;
  };
};

export type iOperation = 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'BATCH_DELETE';

/** Generic Hono context type — compatible with any route path. Used in service functions and utilities. */
export type HonoCtx = Context<{ Bindings: Bindings; Variables: Variables }>;

export interface iLogData {
  timestamp: string;
  operation?: iOperation;
  model?: string;
  user?: {
    id?: string;
    email?: string;
    roles?: string[];
  } | null;
  headers?: Record<string, string> | null;
  data?: any;
  error?: {
    name: string;
    message: string;
    stack?: string;
    code: string;
    statusCode: ContentfulStatusCode;
    cause?: any;
    context?: ErrorContext;
    isOperational: boolean;
  };
  metrics?: {
    executionTime: string;
    startTime?: string;
    endTime?: string;
    memoryUsage?: string;
    queryCount?: number;
    cacheHits?: number;
    cacheMisses?: number;
    cacheHitRate?: string;
    resourceType?: string;
    resourceId?: string;
    isSlowOperation: boolean;
    isCriticalOperation: boolean;
    performanceGrade: string;
    additionalMetrics?: Record<string, any>;
  };
}
